-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg4vskCTwsgMBWtqCbQQVk4jqY1HVsh7S07arjGeXyzB2gCgYIKoZIzj0DAQehRANCAATFE3SrU/TnnnKOyB/2E97D/KQ/JagoPkhgj73SVoXB6viH3bHHPcZsyPej+a9vqml7PlPKC7QDUn6XaExvRyju
-----END PRIVATE KEY-----